export const data = {
    "btc": "Bitcoin",
    "eth": "Ethereum",
    "usdt": "Tether",
    "bnb": "BNB",
    "usdc": "USD Coin",
    "xrp": "XRP",
    "ada": "Cardano",
    "steth": "Lido Staked Ether",
    "doge": "Dogecoin",
    "matic": "Polygon",
    "sol": "Solana",
    "dot": "Polkadot",
    "busd": "Binance USD",
    "ltc": "Litecoin",
    "shib": "Shiba Inu",
    "trx": "TRON",
    "avax": "Avalanche",
    "dai": "Dai",
    "wbtc": "Wrapped Bitcoin",
    "uni": "Uniswap",
    "link": "Chainlink",
    "ton": "Toncoin",
    "leo": "LEO Token",
    "atom": "Cosmos Hub",
    "xmr": "Monero",
    "okb": "OKB",
    "etc": "Ethereum Classic",
    "xlm": "Stellar",
    "icp": "Internet Computer",
    "bch": "Bitcoin Cash",
    "fil": "Filecoin",
    "tusd": "TrueUSD",
    "apt": "Aptos",
    "hbar": "Hedera",
    "arb": "Arbitrum",
    "ldo": "Lido DAO",
    "cro": "Cronos",
    "near": "NEAR Protocol",
    "qnt": "Quant",
    "vet": "VeChain",
    "ape": "ApeCoin",
    "algo": "Algorand",
    "grt": "The Graph",
    "ftm": "Fantom",
    "eos": "EOS",
    "sand": "The Sandbox",
    "usdp": "Pax Dollar",
    "xrd": "Radix",
    "frax": "Frax",
    "mana": "Decentraland",
    "theta": "Theta Network",
    "aave": "Aave",
    "edgt": "Edgecoin",
    "stx": "Stacks",
    "egld": "MultiversX",
    "xtz": "Tezos",
    "flow": "Flow",
    "imx": "ImmutableX",
    "axs": "Axie Infinity",
    "rpl": "Rocket Pool",
    "neo": "NEO",
    "kcs": "KuCoin",
    "snx": "Synthetix Network",
    "crv": "Curve DAO",
    "gt": "Gate",
    "bit": "BitDAO",
    "usdd": "USDD",
    "op": "Optimism",
    "klay": "Klaytn",
    "wbt": "WhiteBIT Token",
    "lunc": "Terra Luna Classic",
    "bsv": "Bitcoin SV",
    "chz": "Chiliz",
    "cake": "PancakeSwap",
    "gmx": "GMX",
    "rndr": "Render",
    "btt": "BitTorrent",
    "mkr": "Maker",
    "cfx": "Conflux",
    "mina": "Mina Protocol",
    "inj": "Injective",
    "xdc": "XDC Network",
    "ht": "Huobi",
    "xec": "eCash",
    "fxs": "Frax Share",
    "dash": "Dash",
    "cspr": "Casper Network",
    "miota": "IOTA",
    "zil": "Zilliqa",
    "bgb": "Bitget Token",
    "paxg": "PAX Gold",
    "tkx": "Tokenize Xchange",
    "twt": "Trust Wallet",
    "reth": "Rocket Pool ETH",
    "xaut": "Tether Gold",
    "ceth": "cETH",
    "flr": "Flare",
    "babydoge": "Baby Doge Coin",
    "gusd": "Gemini Dollar",
    "woo": "WOO Network",
    "kas": "Kaspa",
    "osmo": "Osmosis",
    "lrc": "Loopring",
    "agix": "SingularityNET",
    "rune": "THORChain",
    "cvx": "Convex Finance",
    "1inch": "1inch",
    "enj": "Enjin Coin",
    "ar": "Arweave",
    "dydx": "dYdX",
    "cusdc": "cUSDC",
    "kava": "Kava",
    "bat": "Basic Attention",
    "nexo": "NEXO",
    "fet": "Fetch.ai",
    "okt": "OKT Chain",
    "zec": "Zcash",
    "nxm": "Nexus Mutual",
    "btse": "BTSE Token",
    "mask": "Mask Network",
    "cdai": "cDAI",
    "xem": "NEM",
    "hot": "Holo",
    "ethw": "EthereumPoW",
    "sxp": "SXP",
    "luna": "Terra",
    "dfi": "DeFiChain",
    "rose": "Oasis Network",
    "tfuel": "Theta Fuel",
    "ens": "Ethereum Name Service",
    "wemix": "WEMIX",
    "audio": "Audius",
    "gala": "GALA",
    "qtum": "Qtum",
    "celo": "Celo",
    "azero": "Aleph Zero",
    "xch": "Chia",
    "frxeth": "Frax Ether",
    "ohm": "Olympus",
    "bdx": "Beldex",
    "dcr": "Decred",
    "jasmy": "JasmyCoin",
    "hnt": "Helium",
    "icx": "ICON",
    "floki": "FLOKI",
    "rvn": "Ravencoin",
    "safemoon": "SafeMoon [OLD]",
    "gno": "Gnosis",
    "yfi": "yearn.finance",
    "blur": "Blur",
    "lusd": "Liquity USD",
    "comp": "Compound",
    "astr": "Astar",
    "ksm": "Kusama",
    "ilv": "Illuvium",
    "btg": "Bitcoin Gold",
    "ln": "LINK",
    "ankr": "Ankr Network",
    "cvxcrv": "Convex CRV",
    "bal": "Balancer",
    "one": "Harmony",
    "hbtc": "Huobi BTC",
    "magic": "Magic",
    "bone": "Bone ShibaSwap",
    "gmt": "STEPN",
    "glm": "Golem",
    "jst": "JUST",
    "gfarm2": "Gains Farm",
    "ron": "Ronin",
    "elg": "Escoin",
    "mx": "MX",
    "glmr": "Moonbeam",
    "eurt": "Euro Tether",
    "zrx": "0x Protocol",
    "iotx": "IoTeX",
    "lyxe": "LUKSO",
    "poly": "Polymath",
    "ont": "Ontology",
    "dao": "DAO Maker",
    "astrafer": "Astrafer",
    "kda": "Kadena",
    "band": "Band Protocol",
    "sc": "Siacoin",
    "cdt": "Blox",
    "sushi": "Sushi",
    "amp": "Amp",
    "id": "SPACE ID",
    "ustc": "TerraClassicUSD",
    "iost": "IOST",
    "bico": "Biconomy",
    "multi": "Multichain",
    "waves": "Waves",
    "fuc": "FUBT Token",
    "gns": "Gains Network",
    "ssv": "SSV Network",
    "flux": "Flux",
    "bora": "BORA",
    "joe": "JOE",
    "waxp": "WAX",
    "skl": "SKALE",
    "rsr": "Reserve Rights",
    "krd": "Krypton DAO",
    "ctsi": "Cartesi",
    "alusd": "Alchemix USD",
    "ach": "Alchemy Pay",
    "sfrxeth": "Staked Frax Ether",
    "lqty": "Liquity",
    "omg": "OMG Network",
    "omi": "ECOMI",
    "ocean": "Ocean Protocol",
    "celr": "Celer Network",
    "polyx": "Polymesh",
    "sfp": "SafePal",
    "acs": "Access Protocol",
    "evmos": "Evmos",
    "strd": "Stride",
    "sure": "inSure DeFi",
    "chsb": "SwissBorg",
    "tomi": "tomiNet",
    "brise": "Bitgert",
    "exrd": "e-Radix",
    "lpt": "Livepeer",
    "elon": "Dogelon Mars",
    "tel": "Telcoin",
    "hive": "Hive",
    "syn": "Synapse",
    "kub": "Bitkub Coin",
    "dgb": "DigiByte",
    "lsk": "Lisk",
    "trac": "OriginTrail",
    "core": "Core",
    "deso": "Decentralized Social",
    "pepe": "Pepe",
    "seth2": "sETH2",
    "tribe": "Tribe",
    "elf": "aelf",
    "uma": "UMA",
    "eurs": "STASIS EURO",
    "mmit": "MangoMan Intelligent",
    "ant": "Aragon",
    "scrt": "Secret",
    "zen": "Horizen",
    "stg": "Stargate Finance",
    "canto": "CANTO",
    "ckb": "Nervos Network",
    "nu": "NuCypher",
    "cocos": "COCOS BCX",
    "pla": "PlayDapp",
    "api3": "API3"
}